## ui.R ##
library("rga")
library("shiny")
library("shinydashboard")
library("tidyr")
library("ggplot2")
library("zoo")
library("xts")
library("data.table")
library("scales")
library("plyr")
library("xlsx")
library("ISOweek")

header <- dashboardHeader(title = "NS International" )

sidebar <- dashboardSidebar(
  sidebarMenu(
    menuItem("Sessies", tabName = "traffic"),
    menuItem("Qualified traffic", tabName = "qualified_traffic"),
    menuItem("Conversie", tabName = "conversion"),
    menuItem("Qualified conversie", tabName = "qualified_conversion"),
    menuItem("Transacties", tabName = "transactions"),
    menuItem("AOV", tabName = "aov"),
    menuItem("BVO", tabName = "revenue")
  )
)

body <- dashboardBody(
  tabItems(
    tabItem(tabName = "traffic",
            #box(width = 4, height = "150px", title = "Select graphs", solidHeader = T, status = "primary",
            #checkboxGroupInput("targets", label = "Include:",
              #choices = list("Targets" = T, "Past year" = T), selected = c(T, T))
            #),
            #box(width = 4, height = "150px", title = "Date range", solidHeader = T, status = "primary",
                #dateRangeInput("dateRange",
                               #label = "Select date range",
                               #start = "2016-01-01", end = Sys.Date()-1,
                               #min = "2016-01-01", max = Sys.Date()-1,
                               #separator = " - ", format = "dd/mm/yy",
                               #startview = "month", language = "en",
                               #weekstart = 1) #week should start on Monday, but still begins on default Sunday
            #),
            box(width = 2, height = "135px", title = "Sessies", solidHeader = T, status = "primary",
                selectInput("traffic_channel",
                            "Selecteer kanaal:",
                            choices = c("Totaal" = "total",
                                        "SEO" = "seo",
                                        "SEA" = "sea",
                                        "NS" = "ns",
                                        "Direct" = "direct",
                                        "NSI App" = "nsi_app",
                                        "Affiliates" = "affiliates",
                                        "NSI Email" = "nsi_email",
                                        "Referral" = "referral",
                                        "Retargeting" = "retargeting",
                                        "Facebook" = "facebook",
                                        "Webvertising" = "webvertising",
                                        "NS Email" = "ns_email",
                                        "Other" = "other"))
            ),
            box(width = 10, height = "455px", title = "Sessies", solidHeader = TRUE, status = "primary",
                plotOutput(outputId = "traffic_plot")),
            valueBoxOutput("sessions_targets"),
            valueBoxOutput("sessions_py"),
            valueBoxOutput("sessions_pw")
    ),
    tabItem(tabName = "qualified_traffic",
            box(width = 2, height = "135px", title = "Qualified verkeer", solidHeader = T, status = "primary",
                selectInput("qt_channel",
                            "Selecteer kanaal:",
                            choices = c("Totaal" = "total",
                                        "SEO" = "seo",
                                        "SEA" = "sea",
                                        "NS" = "ns",
                                        "Direct" = "direct",
                                        "NSI App" = "nsi_app",
                                        "Affiliates" = "affiliates",
                                        "NSI Email" = "nsi_email",
                                        "Referral" = "referral",
                                        "Retargeting" = "retargeting",
                                        "Facebook" = "facebook",
                                        "Webvertising" = "webvertising",
                                        "NS Email" = "ns_email",
                                        "Other" = "other"))
            ),
            #box(width = 4, height = "150px", title = "Date range", solidHeader = T, status = "primary",
                #dateRangeInput("dateRange",
                               #label = "Select date range",
                               #start = "2016-01-01", end = Sys.Date()-1,
                               #min = "2016-01-01", max = Sys.Date()-1,
                               #separator = " - ", format = "dd/mm/yy",
                               #startview = "month", language = "en",
                               #weekstart = 1) #week should start on Monday, but still begins on default Sunday
            #),
            box(width = 10, height = "455px", title = "Qualified verkeer", solidHeader = TRUE, status = "primary",
                plotOutput(outputId = "qt_plot")),
            valueBoxOutput("qt_targets"),
            valueBoxOutput("qt_py"),
            valueBoxOutput("qt_pw")
    ),
    tabItem(tabName = "conversion",
            box(width = 2, height= "135px", title = "Conversie", solidHeader = T, status = "primary",
                selectInput("c_channel",
                            "Selecteer kanaal:",
                            choices = c("Totaal" = "total",
                                        "SEO" = "seo",
                                        "SEA" = "sea",
                                        "NS" = "ns",
                                        "Direct" = "direct",
                                        "NSI App" = "nsi_app",
                                        "Affiliates" = "affiliates",
                                        "NSI Email" = "nsi_email",
                                        "Referral" = "referral",
                                        "Retargeting" = "retargeting",
                                        "Facebook" = "facebook",
                                        "Webvertising" = "webvertising",
                                        "NS Email" = "ns_email",
                                        "Other" = "other"))
            ),
            #box(width = 4, height = "150px", title = "Date range", solidHeader = T, status = "primary",
                #dateRangeInput("dateRange",
                                #label = "Select date range",
                                #start = "2016-01-01", end = Sys.Date()-1,
                                #min = "2016-01-01", max = Sys.Date()-1,
                                #separator = " - ", format = "dd/mm/yy",
                                #startview = "month", language = "en",
                                #weekstart = 1) #week should start on Monday, but still begins on default Sunday
            #),
            box(width = 10, height = "455px", title = "Conversie", solidHeader = TRUE, status = "primary",
                plotOutput(outputId = "c_plot")),
            valueBoxOutput("c_targets"),
            valueBoxOutput("c_py"),
            valueBoxOutput("c_pw")
    ),
    tabItem(tabName = "qualified_conversion",
            box(width = 2, height = "135px", title = "Qualified conversie", solidHeader = T, status = "primary",
                selectInput("qc_channel",
                            "Selecteer kanaal:",
                            choices = c("Totaal" = "total",
                                        "SEO" = "seo",
                                        "SEA" = "sea",
                                        "NS" = "ns",
                                        "Direct" = "direct",
                                        "NSI App" = "nsi_app",
                                        "Affiliates" = "affiliates",
                                        "NSI Email" = "nsi_email",
                                        "Referral" = "referral",
                                        "Retargeting" = "retargeting",
                                        "Facebook" = "facebook",
                                        "Webvertising" = "webvertising",
                                        "NS Email" = "ns_email",
                                        "Other" = "other"))
            ),
            #box(width = 4, height = "150px", title = "Date range", solidHeader = T, status = "primary",
                #dateRangeInput("dateRange",
                                #label = "Select date range",
                                #start = "2016-01-01", end = Sys.Date()-1,
                                #min = "2016-01-01", max = Sys.Date()-1,
                                #separator = " - ", format = "dd/mm/yy",
                                #startview = "month", language = "en",
                                #weekstart = 1) #week should start on Monday, but still begins on default Sunday
            #),
            box(width = 10, height = "455px", title = "Qualified conversie", solidHeader = TRUE, status = "primary",
                plotOutput(outputId = "qc_plot")),
            valueBoxOutput("qc_targets"),
            valueBoxOutput("qc_py"),
            valueBoxOutput("qc_pw")
    ),
    tabItem(tabName = "transactions",
            box(width = 2, height = "135px", title = "Transacties", solidHeader = T, status = "primary",
                selectInput("trans_channel",
                            "Selecteer kanaal:",
                            choices = c("Totaal" = "total",
                                        "SEO" = "seo",
                                        "SEA" = "sea",
                                        "NS" = "ns",
                                        "Direct" = "direct",
                                        "NSI App" = "nsi_app",
                                        "Affiliates" = "affiliates",
                                        "NSI Email" = "nsi_email",
                                        "Referral" = "referral",
                                        "Retargeting" = "retargeting",
                                        "Facebook" = "facebook",
                                        "Webvertising" = "webvertising",
                                        "NS Email" = "ns_email",
                                        "Other" = "other"))
            ),
            #box(width = 4, height = "150px", title = "Date range", solidHeader = T, status = "primary",
                #dateRangeInput("dateRange",
                                #label = "Select date range",
                                #start = "2016-01-01", end = Sys.Date()-1,
                                #min = "2016-01-01", max = Sys.Date()-1,
                                #separator = " - ", format = "dd/mm/yy",
                                #startview = "month", language = "en",
                                #weekstart = 1) #week should start on Monday, but still begins on default Sunday
            #),
            box(width = 10, height = "455px", title = "Transacties", solidHeader = TRUE, status = "primary",
                plotOutput(outputId = "trans_plot")),
            valueBoxOutput("trans_targets"),
            valueBoxOutput("trans_py"),
            valueBoxOutput("trans_pw")
    ),
    tabItem(tabName = "aov",
            box(width = 2, height = "135px", title = "AOV", solidHeader = T, status = "primary",
                selectInput("aov_channel",
                            "Selecteer kanaal:",
                            choices = c("Totaal" = "total",
                                        "SEO" = "seo",
                                        "SEA" = "sea",
                                        "NS" = "ns",
                                        "Direct" = "direct",
                                        "NSI App" = "nsi_app",
                                        "Affiliates" = "affiliates",
                                        "NSI Email" = "nsi_email",
                                        "Referral" = "referral",
                                        "Retargeting" = "retargeting",
                                        "Facebook" = "facebook",
                                        "Webvertising" = "webvertising",
                                        "NS Email" = "ns_email",
                                        "Other" = "other"))
            ),
            #box(width = 4, height = "150px", title = "Date range", solidHeader = T, status = "primary",
                #dateRangeInput("dateRange",
                                #label = "Select date range",
                                #start = "2016-01-01", end = Sys.Date()-1,
                                #min = "2016-01-01", max = Sys.Date()-1,
                                #separator = " - ", format = "dd/mm/yy",
                                #startview = "month", language = "en",
                                #weekstart = 1) #week should start on Monday, but still begins on default Sunday
            #),
            box(width = 10, height = "455px", title = "AOV", solidHeader = TRUE, status = "primary",
                plotOutput(outputId = "aov_plot")),
            valueBoxOutput("aov_targets"),
            valueBoxOutput("aov_py"),
            valueBoxOutput("aov_pw")
    ),
    tabItem(tabName = "revenue",
            box(width = 2, height = "135px", title = "BVO", solidHeader = T, status = "primary",
                selectInput("rev_channel",
                            "Selecteer kanaal:",
                            choices = c("Totaal" = "total",
                                        "SEO" = "seo",
                                        "SEA" = "sea",
                                        "NS" = "ns",
                                        "Direct" = "direct",
                                        "NSI App" = "nsi_app",
                                        "Affiliates" = "affiliates",
                                        "NSI Email" = "nsi_email",
                                        "Referral" = "referral",
                                        "Retargeting" = "retargeting",
                                        "Facebook" = "facebook",
                                        "Webvertising" = "webvertising",
                                        "NS Email" = "ns_email",
                                        "Other" = "other"))
            ),
            #box(width = 4, height = "150px", title = "Date range", solidHeader = T, status = "primary",
                #dateRangeInput("dateRange",
                                #label = "Select date range",
                                #start = "2016-01-01", end = Sys.Date()-1,
                                #min = "2016-01-01", max = Sys.Date()-1,
                                #separator = " - ", format = "dd/mm/yy",
                                #startview = "month", language = "en",
                                #weekstart = 1) #week should start on Monday, but still begins on default Sunday
            #),
            box(width = 10, height = "455px", title = "BVO", solidHeader = TRUE, status = "primary",
                plotOutput(outputId = "rev_plot")),
            valueBoxOutput("rev_targets"),
            valueBoxOutput("rev_py"),
            valueBoxOutput("rev_pw")
      )
  )
)

dashboardPage(header, sidebar, body)
